export const countries = [
  { value: "AR", label: "🇦🇷 Argentina", dialCode: "+54" },
  { value: "AU", label: "🇦🇺 Australia", dialCode: "+61" },
  { value: "AT", label: "🇦🇹 Austria", dialCode: "+43" },
  { value: "BE", label: "🇧🇪 Belgium", dialCode: "+32" },
  { value: "BR", label: "🇧🇷 Brazil", dialCode: "+55" },
  { value: "BG", label: "🇧🇬 Bulgaria", dialCode: "+359" },
  { value: "CA", label: "🇨🇦 Canada", dialCode: "+1" },
  { value: "CL", label: "🇨🇱 Chile", dialCode: "+56" },
  { value: "CN", label: "🇨🇳 China", dialCode: "+86" },
  { value: "CO", label: "🇨🇴 Colombia", dialCode: "+57" },
  { value: "CZ", label: "🇨🇿 Czech Republic", dialCode: "+420" },
  { value: "DK", label: "🇩🇰 Denmark", dialCode: "+45" },
  { value: "EG", label: "🇪🇬 Egypt", dialCode: "+20" },
  { value: "FI", label: "🇫🇮 Finland", dialCode: "+358" },
  { value: "FR", label: "🇫🇷 France", dialCode: "+33" },
  { value: "DE", label: "🇩🇪 Germany", dialCode: "+49" },
  { value: "GR", label: "🇬🇷 Greece", dialCode: "+30" },
  { value: "HU", label: "🇭🇺 Hungary", dialCode: "+36" },
  { value: "IN", label: "🇮🇳 India", dialCode: "+91" },
  { value: "ID", label: "🇮🇩 Indonesia", dialCode: "+62" },
  { value: "IE", label: "🇮🇪 Ireland", dialCode: "+353" },
  { value: "IT", label: "🇮🇹 Italy", dialCode: "+39" },
  { value: "JP", label: "🇯🇵 Japan", dialCode: "+81" },
  { value: "KR", label: "🇰🇷 South Korea", dialCode: "+82" },
  { value: "MY", label: "🇲🇾 Malaysia", dialCode: "+60" },
  { value: "MX", label: "🇲🇽 Mexico", dialCode: "+52" },
  { value: "NL", label: "🇳🇱 Netherlands", dialCode: "+31" },
  { value: "NZ", label: "🇳🇿 New Zealand", dialCode: "+64" },
  { value: "NG", label: "🇳🇬 Nigeria", dialCode: "+234" },
  { value: "NO", label: "🇳🇴 Norway", dialCode: "+47" },
  { value: "PK", label: "🇵🇰 Pakistan", dialCode: "+92" },
  { value: "PH", label: "🇵🇭 Philippines", dialCode: "+63" },
  { value: "PL", label: "🇵🇱 Poland", dialCode: "+48" },
  { value: "PT", label: "🇵🇹 Portugal", dialCode: "+351" },
  { value: "RO", label: "🇷🇴 Romania", dialCode: "+40" },
  { value: "RU", label: "🇷🇺 Russia", dialCode: "+7" },
  { value: "SA", label: "🇸🇦 Saudi Arabia", dialCode: "+966" },
  { value: "SK", label: "🇸🇰 Slovakia", dialCode: "+421" },
  { value: "ES", label: "🇪🇸 Spain", dialCode: "+34" },
  { value: "SE", label: "🇸🇪 Sweden", dialCode: "+46" },
  { value: "CH", label: "🇨🇭 Switzerland", dialCode: "+41" },
  { value: "TH", label: "🇹🇭 Thailand", dialCode: "+66" },
  { value: "TR", label: "🇹🇷 Turkey", dialCode: "+90" },
  { value: "AE", label: "🇦🇪 United Arab Emirates", dialCode: "+971" },
  { value: "GB", label: "🇬🇧 United Kingdom", dialCode: "+44" },
  { value: "US", label: "🇺🇸 United States", dialCode: "+1" },
  { value: "VN", label: "🇻🇳 Vietnam", dialCode: "+84" },
  { value: "ZA", label: "🇿🇦 South Africa", dialCode: "+27" },
]
